# DSA4156 Lab: Inmon vs. Kimball on Sample Superstore
## Template notebook

| | |
|---|---|
| **Group name** | *fill in* |
| **Members** | *fill in* |

You will build two data warehouses from the same source data, in one PostgreSQL database:

- `staging`: raw and cleaned copies of the source files
- `inmon`: a **3NF** enterprise warehouse
- `kimball`: a **denormalized** dimensional model (star or snowflake schema)

**Rules**
- Cells marked `# TODO` are yours to complete. You may add as many cells as you need.
- You may transform with pandas, SQL, or both, but every step must run from this notebook.
- Before submitting, run **Kernel > Restart & Run All** and save the notebook *with outputs*.
- Your data model diagrams go in the PDF report, not here.

## 0. Setup

**Requirements**
- PostgreSQL **15 or newer** (16 recommended). Version 15 is needed for `UNIQUE NULLS NOT DISTINCT`.
- Python packages: `pandas`, `sqlalchemy>=2.0`, `psycopg2-binary`

Create an empty database first, for example in `psql`:
```sql
CREATE DATABASE superstore_dw;
```
Then set your connection string below, or set the `DW_URL` environment variable.
**Do not commit real passwords** in the notebook you submit.

In [ ]:
import os, re
from pathlib import Path

import numpy as np
import pandas as pd
from sqlalchemy import create_engine, text
from sqlalchemy import types as sa_types

DATA_DIR = Path("data")
DW_URL = os.getenv("DW_URL", "postgresql+psycopg2://postgres:password@localhost:5432/superstore_dw")

engine = create_engine(DW_URL, future=True)

def run_sql(sql: str) -> None:
    """Execute one or more SQL statements (DDL or DML) in a single transaction."""
    with engine.begin() as conn:
        conn.exec_driver_sql(sql)

def q(sql: str, **params) -> pd.DataFrame:
    """Run a SELECT and return the result as a DataFrame."""
    with engine.connect() as conn:
        return pd.read_sql(text(sql), conn, params=params)

def table_counts(schema: str) -> pd.DataFrame:
    """Row count of every table (partitioned parents included, partitions excluded) in a schema."""
    tables = q("""
        SELECT c.relname AS table_name
        FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = :s AND c.relkind IN ('r', 'p') AND NOT c.relispartition
        ORDER BY 1""", s=schema)["table_name"]
    rows = [(t, int(q(f'SELECT count(*) AS n FROM "{schema}"."{t}"')["n"][0])) for t in tables]
    return pd.DataFrame(rows, columns=["table_name", "row_count"])

print(q("SELECT version()")["version"][0])

PostgreSQL 18.6 on x86_64-windows, compiled by msvc-19.44.35228, 64-bit


## 1. Extract

The source system gave us three files (originally three sheets of one workbook):

| File | Contents |
|---|---|
| `orders.csv` | One row per order line (flat, denormalized, 21 columns) |
| `returns.csv` | Orders that were returned |
| `people.csv` | The regional manager of each region |

We read everything **as text** so that nothing is silently converted, then copy the raw data into a
`staging` schema. Staging keeps an untouched copy of the source so the warehouse can always be rebuilt.

In [39]:
raw_orders  = pd.read_csv(DATA_DIR / "orders.csv",  dtype=str, keep_default_na=False)
raw_returns = pd.read_csv(DATA_DIR / "returns.csv", dtype=str, keep_default_na=False)
raw_people  = pd.read_csv(DATA_DIR / "people.csv",  dtype=str, keep_default_na=False)

def snake(col: str) -> str:
    return re.sub(r"[^0-9a-z]+", "_", col.strip().lower()).strip("_")

run_sql("CREATE SCHEMA IF NOT EXISTS staging;")
for name, df in [("orders_raw", raw_orders), ("returns_raw", raw_returns), ("people_raw", raw_people)]:
    df.rename(columns=snake).to_sql(name, engine, schema="staging", if_exists="replace", index=False)

print({n: len(d) for n, d in [("orders", raw_orders), ("returns", raw_returns), ("people", raw_people)]})
raw_orders.head()

{'orders': 9994, 'returns': 800, 'people': 4}


,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2017-152156,11/8/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0,41.9136
1,2,CA-2017-152156,11/8/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0,219.582
2,3,CA-2017-138688,6/12/2017,6/16/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0,6.8714
3,4,US-2016-108966,10/11/2016,10/18/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.031
4,5,US-2016-108966,10/11/2016,10/18/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368,2,0.2,2.5164


In [40]:
raw_orders['Order ID'].duplicated().sum()

np.int64(4985)

### 1.1 Profile the source: find the functional dependencies

Before designing any model, test which columns determine which. `A -> B` holds when every value of `A`
maps to exactly one value of `B`. The count below is the number of `A` values that break the rule.
These results are the evidence for your normalization decisions in the report.

### **Check Data Types**

In [41]:
orders = raw_orders.rename(columns=snake)
people = raw_people.rename(columns=snake)
returns_df = raw_returns.rename(columns=snake)

In [42]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   row_id         9994 non-null   str  
 1   order_id       9994 non-null   str  
 2   order_date     9994 non-null   str  
 3   ship_date      9994 non-null   str  
 4   ship_mode      9994 non-null   str  
 5   customer_id    9994 non-null   str  
 6   customer_name  9994 non-null   str  
 7   segment        9994 non-null   str  
 8   country        9994 non-null   str  
 9   city           9994 non-null   str  
 10  state          9994 non-null   str  
 11  postal_code    9994 non-null   str  
 12  region         9994 non-null   str  
 13  product_id     9994 non-null   str  
 14  category       9994 non-null   str  
 15  sub_category   9994 non-null   str  
 16  product_name   9994 non-null   str  
 17  sales          9994 non-null   str  
 18  quantity       9994 non-null   str  
 19  discount       99

In [43]:
orders.isna().sum()

row_id           0
order_id         0
order_date       0
ship_date        0
ship_mode        0
customer_id      0
customer_name    0
segment          0
country          0
city             0
state            0
postal_code      0
region           0
product_id       0
category         0
sub_category     0
product_name     0
sales            0
quantity         0
discount         0
profit           0
dtype: int64

In [44]:
len(orders[(orders['city'] == 'Burlington') & (orders['state'] == 'Vermont')])

11

In [45]:
orders[(orders['city'] == 'Burlington') & (orders['state'] == 'Vermont')].T

,2234,5274,8798,9146,9147,9148,9386,9387,9388,9389,9741
row_id,2235,5275,8799,9147,9148,9149,9387,9388,9389,9390,9742
order_id,CA-2018-104066,CA-2016-162887,US-2017-150140,US-2017-165505,US-2017-165505,US-2017-165505,US-2018-127292,US-2018-127292,US-2018-127292,US-2018-127292,CA-2016-117086
order_date,12/5/2018,11/7/2016,4/6/2017,1/23/2017,1/23/2017,1/23/2017,1/19/2018,1/19/2018,1/19/2018,1/19/2018,11/8/2016
ship_date,12/10/2018,11/9/2016,4/10/2017,1/27/2017,1/27/2017,1/27/2017,1/23/2018,1/23/2018,1/23/2018,1/23/2018,11/12/2016
ship_mode,Standard Class,Second Class,Standard Class,Standard Class,Standard Class,Standard Class,Standard Class,Standard Class,Standard Class,Standard Class,Standard Class
customer_id,QJ-19255,SV-20785,VM-21685,CB-12535,CB-12535,CB-12535,RM-19375,RM-19375,RM-19375,RM-19375,QJ-19255
customer_name,Quincy Jones,Stewart Visinsky,Valerie Mitchum,Claudia Bergmann,Claudia Bergmann,Claudia Bergmann,Raymond Messe,Raymond Messe,Raymond Messe,Raymond Messe,Quincy Jones
segment,Corporate,Consumer,Home Office,Corporate,Corporate,Corporate,Consumer,Consumer,Consumer,Consumer,Corporate
country,United States,United States,United States,United States,United States,United States,United States,United States,United States,United States,United States
city,Burlington,Burlington,Burlington,Burlington,Burlington,Burlington,Burlington,Burlington,Burlington,Burlington,Burlington


We have observed that the null values for postal_code are all from Burlington, Vermont. According to codigo-postal.co, the standard postal code for Burlington, Vermont is 05401, hence we fill the null values with it. 


Reference: https://codigo-postal.co/en-us/usa/vermont/burlington/

In [46]:
orders['postal_code'].fillna('05401', inplace=True)

C:\Users\L\AppData\Local\Temp\ipykernel_18644\1312218500.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  orders['postal_code'].fillna('05401', inplace=True)


0       42420
1       42420
2       90036
3       33311
4       33311
5       90032
6       90032
7       90032
8       90032
9       90032
10      90032
11      90032
12      28027
13      98103
14      76106
15      76106
16      53711
17      84084
18      94109
19      94109
20      94109
21      68025
22      68025
23      19140
24      84057
25      90049
26      90049
27      19140
28      19140
29      19140
30      19140
31      19140
32      19140
33      19140
34      77095
35      75080
36      75080
37      77041
38      77041
39      77041
40      77041
41      60540
42      90049
43      32935
44      55122
45      55122
46      48185
47      19901
48      19901
49      47150
50      47150
51      47150
52      47150
53      10024
54      10024
55      12180
56      12180
57      12180
58      12180
59      12180
60      12180
61      12180
62      90004
63      90004
64      90004
65      90004
66      60610
67      85234
68      85234
69      22153
70      10009
71    

In [47]:
orders.isna().sum()

row_id           0
order_id         0
order_date       0
ship_date        0
ship_mode        0
customer_id      0
customer_name    0
segment          0
country          0
city             0
state            0
postal_code      0
region           0
product_id       0
category         0
sub_category     0
product_name     0
sales            0
quantity         0
discount         0
profit           0
dtype: int64

In [48]:
orders.dropna(subset=['postal_code'], inplace=True)

In [49]:
people.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   regional_manager  4 non-null      str  
 1   region            4 non-null      str  
dtypes: str(2)
memory usage: 196.0 bytes


In [50]:
returns_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   returned  800 non-null    str  
 1   order_id  800 non-null    str  
dtypes: str(2)
memory usage: 12.6 KB


In [51]:
returns_df 

,returned,order_id
0,Yes,CA-2015-100762
1,Yes,CA-2015-100762
2,Yes,CA-2015-100762
3,Yes,CA-2015-100762
4,Yes,CA-2015-100867
5,Yes,CA-2015-102652
6,Yes,CA-2015-102652
7,Yes,CA-2015-102652
8,Yes,CA-2015-102652
9,Yes,CA-2015-103373


order_id repeats. This might be due to the fact that an order can contain multiple products, hence when an order is returned, it is recorded as the number of products for that order.

In [52]:
orders[orders['order_id'] == 'CA-2015-100762']

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,postal_code,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit
6314,6315,CA-2015-100762,11/24/2015,11/29/2015,Standard Class,NG-18355,Nat Gilpin,Corporate,United States,Jackson,...,49201,Central,OFF-AR-10000380,Office Supplies,Art,"Hunt PowerHouse Electric Pencil Sharpener, Blue",151.92,4,0,45.576
6315,6316,CA-2015-100762,11/24/2015,11/29/2015,Standard Class,NG-18355,Nat Gilpin,Corporate,United States,Jackson,...,49201,Central,OFF-LA-10003930,Office Supplies,Labels,"Dot Matrix Printer Tape Reel Labels, White, 50...",196.62,2,0,96.3438
6316,6317,CA-2015-100762,11/24/2015,11/29/2015,Standard Class,NG-18355,Nat Gilpin,Corporate,United States,Jackson,...,49201,Central,OFF-PA-10001815,Office Supplies,Paper,Xerox 1885,144.12,3,0,69.1776
6317,6318,CA-2015-100762,11/24/2015,11/29/2015,Standard Class,NG-18355,Nat Gilpin,Corporate,United States,Jackson,...,49201,Central,OFF-PA-10004082,Office Supplies,Paper,Adams Telephone Message Book w/Frequently-Call...,15.96,2,0,7.98


And indeed, we find that there are four of these orders, just like how the order_id for this order occurs four times in the returns data. We can further check this for all unique values of order_id in the orders table, to see if it occurs the same number of times in the returns table. 

In [53]:
def compare_value_counts(df1, df2, col1, col2, id_name="value"):
    """
    Check whether each unique value in col1 (df1) occurs the same number of
    times as in col2 (df2).

    Parameters
    ----------
    df1, df2 : pd.DataFrame
        The two dataframes to compare.
    col1, col2 : str
        Column names to compare (can differ between df1 and df2).
    id_name : str
        Label to use for the compared column in the output (cosmetic).

    Returns
    -------
    pd.DataFrame
        One row per unique value found in either dataframe, with:
        - count_df1, count_df2 : occurrence counts (0 if missing)
        - match : True if counts are equal
    """
    counts1 = df1[col1].value_counts().rename("count_df1")
    counts2 = df2[col2].value_counts().rename("count_df2")

    comparison = pd.concat([counts1, counts2], axis=1).fillna(0)
    comparison[["count_df1", "count_df2"]] = comparison[["count_df1", "count_df2"]].astype(int)
    comparison["match"] = comparison["count_df1"] == comparison["count_df2"]

    comparison.index.name = id_name
    return comparison.reset_index()

In [54]:
result = compare_value_counts(orders, returns_df, "order_id", "order_id")
result[(result.count_df1 > 0) & (result.count_df2 > 0)]

,value,count_df1,count_df2,match
0,CA-2018-100111,14,14,True
3,CA-2017-165330,11,11,True
9,CA-2016-164882,9,9,True
18,US-2018-118087,8,8,True
22,CA-2018-161956,8,8,True
29,CA-2015-142769,8,8,True
35,CA-2017-111682,7,7,True
36,CA-2017-145583,7,7,True
47,US-2018-109253,7,7,True
50,CA-2015-110786,7,7,True


Confirming our observations, we drop the duplicates of order_id in returns.

In [55]:
returns_df = returns_df.drop_duplicates(subset='order_id')
returns_df.duplicated().sum()

np.int64(0)

### **Test Functional Dependencies**

In [56]:
def fd_violations(df: pd.DataFrame, lhs, rhs: str) -> int:
    """Number of distinct LHS values that map to more than one RHS value."""
    counts = df.groupby(lhs, dropna=False)[rhs].nunique(dropna=False)
    return int((counts > 1).sum())

In [57]:
from itertools import permutations
#lhs->rhs

def check_all_fds(df: pd.DataFrame) -> pd.DataFrame:
    columns = list(df.columns)
    results = []

    for lhs, rhs in permutations(columns, 2):
        violations = fd_violations(df, lhs, rhs)
        results.append(
            {
                "Determinant": lhs,
                "Dependent": rhs,
                "Violations": violations,
                "Holds": violations == 0,
            }
        )

    return pd.DataFrame(results, columns=["Determinant", "Dependent", "Violations", "Holds"])

In [58]:
# Example
#print("order_id -> customer_id violations:", fd_violations(orders, "order_id", "customer_id"))

# TODO: test every dependency you think might hold, e.g. customer -> segment, product -> category,
#       postal code -> city, city -> state, state -> region, and so on.
#       Build a small table of results (determinant, dependent, violations) to put in your report.

#testing all columns for orders
pd.set_option("display.max_rows", None)
order_dependency_df = check_all_fds(orders)

In [59]:
order_dependency_df[order_dependency_df["Violations"] > 0].sort_values("Violations", ascending=False)

,Determinant,Dependent,Violations,Holds
20,order_id,row_id,2471,False
39,order_id,profit,2471,False
36,order_id,sales,2471,False
35,order_id,product_name,2469,False
32,order_id,product_id,2469,False
34,order_id,sub_category,2346,False
37,order_id,quantity,2237,False
340,sales,row_id,1986,False
341,sales,order_id,1985,False
343,sales,ship_date,1985,False


In [60]:
#reset display max rows
pd.reset_option("display.max_rows")

### **Check ID Uniqueness in the orders data** 

In [61]:
def check_id_uniqueness(df: pd.DataFrame) -> pd.DataFrame:
    """Check uniqueness of every column whose name contains 'ID'.

    Columns are matched if their name contains 'ID' (case-insensitive). A
    column is considered unique when it has no duplicate non-null values.
    'n duplicates' counts the number of extra occurrences beyond the first,
    i.e. total rows minus the number of distinct non-null values.

    Returns a DataFrame with columns: "column name", "unique", "n duplicates".
    """
    id_cols = [col for col in df.columns if "id" in str(col).lower()]

    results = []
    for col in id_cols:
        non_null = df[col].dropna()
        n_duplicates = int(non_null.duplicated().sum())
        results.append(
            {
                "column name": col,
                "unique": n_duplicates == 0,
                "n duplicates": n_duplicates,
            }
        )

    return pd.DataFrame(
        results, columns=["column name", "unique", "n duplicates"]
    )

In [62]:
check_id_uniqueness(orders)

,column name,unique,n duplicates
0,row_id,True,0
1,order_id,False,4985
2,customer_id,False,9201
3,product_id,False,8132


The criteria for the helper function used is that the column must simply have 'id' in the name, however some columns CAN serve as identifiers without explicitly having 'id' in the name such as 'Region' for a normalized database with a Region table (Region is also present in the 'People' table). For such cases, it is manually checked. 

In [63]:
# TODO: look for data quality problems before you design anything. For example:
#   - Is (order_id, product_id) unique? What should the order-line key be?
#   - Do all postal codes have 5 digits? Are any missing?
#   - Do all IDs follow the same format?
#   - Does returns.csv contain duplicates?
# The source contains several such problems. Your report must list the ones you found and how you handled them.


### **Checking one-to-one mapping between order_id and order_date**

In some case for the orders table/dataframe, for a row with a value of OrderID, A, its Order Date is B such that if A occurs in one row as the ID, its Date is B. It may repeat but its always A-B for any row A or B occurs in. We can verify this below:

In [64]:
n_ids = orders["order_id"].nunique()
n_dates = orders["order_date"].nunique()
n_pairs = len(orders[["order_id", "order_date"]].drop_duplicates())

print(n_ids == n_dates == n_pairs)

False


In [65]:
print(order_dependency_df[(order_dependency_df["Determinant"] == "order_id")&(order_dependency_df["Dependent"] == "order_date")])
print(order_dependency_df[(order_dependency_df["Determinant"] == "order_date")& (order_dependency_df["Dependent"] == "order_id")])

   Determinant   Dependent  Violations  Holds
21    order_id  order_date           0   True
   Determinant Dependent  Violations  Holds
41  order_date  order_id        1014  False


This turns out to be false, or not true both ways. Every order_id maps to exactly one order_date but some dates have more than one order_id hence a many-to-one relationship between order_id and order_date. Altough trivial, its still worth checking for data integrity. 

### **Checking Missing Values**

In [66]:
def report_missing_vals(df: pd.DataFrame) -> pd.DataFrame:
    missing = df.isna().sum()
    report = pd.DataFrame(
        {
            "column": missing.index,
            "missing values": missing.values,
            "percentage": (missing.values / len(df)) * 100,
        }
    )
    return report

In [67]:
report_missing_vals(orders)

,column,missing values,percentage
0,row_id,0,0.0
1,order_id,0,0.0
2,order_date,0,0.0
3,ship_date,0,0.0
4,ship_mode,0,0.0
5,customer_id,0,0.0
6,customer_name,0,0.0
7,segment,0,0.0
8,country,0,0.0
9,city,0,0.0


In [68]:
report_missing_vals(returns_df)

,column,missing values,percentage
0,returned,0,0.0
1,order_id,0,0.0


### **Checking Postal Codes**
By definition (from the hint in the instructions), postal codes must be 5-digits. 

In [69]:
len(orders[orders["postal_code"].astype(str).str.len() != 5])

449

In [70]:
orders[orders["postal_code"].astype(str).str.len() != 5].T

,185,197,267,298,299,300,301,302,306,307,...,9784,9811,9812,9813,9814,9889,9936,9967,9968,9969
row_id,186,198,268,299,300,301,302,303,307,308,...,9785,9812,9813,9814,9815,9890,9937,9968,9969,9970
order_id,CA-2017-105018,CA-2018-107720,CA-2017-111010,CA-2017-142545,CA-2017-142545,CA-2017-142545,CA-2017-142545,CA-2017-142545,CA-2015-111003,CA-2015-111003,...,CA-2016-149748,CA-2017-117583,CA-2017-117583,CA-2017-117583,CA-2017-117583,CA-2018-166499,CA-2018-132955,CA-2018-153871,CA-2018-153871,CA-2018-153871
order_date,11/28/2017,11/6/2018,1/22/2017,10/28/2017,10/28/2017,10/28/2017,10/28/2017,10/28/2017,6/1/2015,6/1/2015,...,5/31/2016,11/27/2017,11/27/2017,11/27/2017,11/27/2017,3/19/2018,6/24/2018,12/11/2018,12/11/2018,12/11/2018
ship_date,12/2/2017,11/13/2018,1/28/2017,11/3/2017,11/3/2017,11/3/2017,11/3/2017,11/3/2017,6/6/2015,6/6/2015,...,6/2/2016,11/30/2017,11/30/2017,11/30/2017,11/30/2017,3/20/2018,6/28/2018,12/17/2018,12/17/2018,12/17/2018
ship_mode,Standard Class,Standard Class,Standard Class,Standard Class,Standard Class,Standard Class,Standard Class,Standard Class,Standard Class,Standard Class,...,Second Class,First Class,First Class,First Class,First Class,First Class,Standard Class,Standard Class,Standard Class,Standard Class
customer_id,SK-19990,VM-21685,PG-18895,JD-15895,JD-15895,JD-15895,JD-15895,JD-15895,CR-12625,CR-12625,...,EM-13825,CB-12025,CB-12025,CB-12025,CB-12025,VG-21805,SC-20575,RB-19435,RB-19435,RB-19435
customer_name,Sally Knutson,Valerie Mitchum,Paul Gonzalez,Jonathan Doherty,Jonathan Doherty,Jonathan Doherty,Jonathan Doherty,Jonathan Doherty,Corey Roper,Corey Roper,...,Elizabeth Moffitt,Cassandra Brandow,Cassandra Brandow,Cassandra Brandow,Cassandra Brandow,Vivek Grady,Sonia Cooley,Richard Bierner,Richard Bierner,Richard Bierner
segment,Consumer,Home Office,Consumer,Corporate,Corporate,Corporate,Corporate,Corporate,Home Office,Home Office,...,Corporate,Consumer,Consumer,Consumer,Consumer,Corporate,Consumer,Consumer,Consumer,Consumer
country,United States,United States,United States,United States,United States,United States,United States,United States,United States,United States,...,United States,United States,United States,United States,United States,United States,United States,United States,United States,United States
city,Fairfield,Westfield,Morristown,Belleville,Belleville,Belleville,Belleville,Belleville,Lakewood,Lakewood,...,Paterson,East Orange,East Orange,East Orange,East Orange,Lakewood,Cranston,Plainfield,Plainfield,Plainfield


Upon checking, some of the observations where the postal code is 4 digits simply lack a 0 at the start so 6824 -> 06824, which maps to Conneticut. We apply this rule for all 4 digit zip codes

In [71]:
#add a zero to the prefix of all postal_codes where its length is 4
orders["postal_code"] = orders["postal_code"].astype(str).str.zfill(5)

In [72]:
len(orders[orders["postal_code"].astype(str).str.len() != 5])

0

In [73]:
orders.head(21).T

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
row_id,1,2,3,4,5,6,7,8,9,10,...,12,13,14,15,16,17,18,19,20,21
order_id,CA-2017-152156,CA-2017-152156,CA-2017-138688,US-2016-108966,US-2016-108966,CA-2015-115812,CA-2015-115812,CA-2015-115812,CA-2015-115812,CA-2015-115812,...,CA-2015-115812,CA-2018-114412,CA-2017-161389,US-2016-118983,US-2016-118983,CA-2015-105893,CA-2015-167164,CA-2015-143336,CA-2015-143336,CA-2015-143336
order_date,11/8/2017,11/8/2017,6/12/2017,10/11/2016,10/11/2016,6/9/2015,6/9/2015,6/9/2015,6/9/2015,6/9/2015,...,6/9/2015,4/15/2018,12/5/2017,11/22/2016,11/22/2016,11/11/2015,5/13/2015,8/27/2015,8/27/2015,8/27/2015
ship_date,11/11/2017,11/11/2017,6/16/2017,10/18/2016,10/18/2016,6/14/2015,6/14/2015,6/14/2015,6/14/2015,6/14/2015,...,6/14/2015,4/20/2018,12/10/2017,11/26/2016,11/26/2016,11/18/2015,5/15/2015,9/1/2015,9/1/2015,9/1/2015
ship_mode,Second Class,Second Class,Second Class,Standard Class,Standard Class,Standard Class,Standard Class,Standard Class,Standard Class,Standard Class,...,Standard Class,Standard Class,Standard Class,Standard Class,Standard Class,Standard Class,Second Class,Second Class,Second Class,Second Class
customer_id,CG-12520,CG-12520,DV-13045,SO-20335,SO-20335,BH-11710,BH-11710,BH-11710,BH-11710,BH-11710,...,BH-11710,AA-10480,IM-15070,HP-14815,HP-14815,PK-19075,AG-10270,ZD-21925,ZD-21925,ZD-21925
customer_name,Claire Gute,Claire Gute,Darrin Van Huff,Sean O'Donnell,Sean O'Donnell,Brosina Hoffman,Brosina Hoffman,Brosina Hoffman,Brosina Hoffman,Brosina Hoffman,...,Brosina Hoffman,Andrew Allen,Irene Maddox,Harold Pawlan,Harold Pawlan,Pete Kriz,Alejandro Grove,Zuschuss Donatelli,Zuschuss Donatelli,Zuschuss Donatelli
segment,Consumer,Consumer,Corporate,Consumer,Consumer,Consumer,Consumer,Consumer,Consumer,Consumer,...,Consumer,Consumer,Consumer,Home Office,Home Office,Consumer,Consumer,Consumer,Consumer,Consumer
country,United States,United States,United States,United States,United States,United States,United States,United States,United States,United States,...,United States,United States,United States,United States,United States,United States,United States,United States,United States,United States
city,Henderson,Henderson,Los Angeles,Fort Lauderdale,Fort Lauderdale,Los Angeles,Los Angeles,Los Angeles,Los Angeles,Los Angeles,...,Los Angeles,Concord,Seattle,Fort Worth,Fort Worth,Madison,West Jordan,San Francisco,San Francisco,San Francisco


In [74]:
#display unique values for categorical columns
print(orders['country'].value_counts())
print('-'*20)
print(orders['ship_mode'].value_counts())
print('-'*20)
print(orders["segment"].value_counts())
print('-'*20)
print(orders["region"].value_counts())
print('-'*20)
print(orders['category'].value_counts())
print('-'*20)
print(orders['sub_category'].value_counts())

country
United States    9994
Name: count, dtype: int64
--------------------
ship_mode
Standard Class    5968
Second Class      1945
First Class       1538
Same Day           543
Name: count, dtype: int64
--------------------
segment
Consumer       5191
Corporate      3020
Home Office    1783
Name: count, dtype: int64
--------------------
region
West       3203
East       2848
Central    2323
South      1620
Name: count, dtype: int64
--------------------
category
Office Supplies    6026
Furniture          2121
Technology         1847
Name: count, dtype: int64
--------------------
sub_category
Binders        1523
Paper          1370
Furnishings     957
Phones          889
Storage         846
Art             796
Accessories     775
Chairs          617
Appliances      466
Labels          364
Tables          319
Envelopes       254
Bookcases       228
Fasteners       217
Supplies        190
Machines        115
Copiers          68
Name: count, dtype: int64


The columns for an orders table must depend on order_id, in other words order_id cannot repeat and is the unique identifier. Other id's (such as customer_id) can repeat but are better referenced from its own table (ideally a customers table).

In [75]:
orders.head().T

,0,1,2,3,4
row_id,1,2,3,4,5
order_id,CA-2017-152156,CA-2017-152156,CA-2017-138688,US-2016-108966,US-2016-108966
order_date,11/8/2017,11/8/2017,6/12/2017,10/11/2016,10/11/2016
ship_date,11/11/2017,11/11/2017,6/16/2017,10/18/2016,10/18/2016
ship_mode,Second Class,Second Class,Second Class,Standard Class,Standard Class
customer_id,CG-12520,CG-12520,DV-13045,SO-20335,SO-20335
customer_name,Claire Gute,Claire Gute,Darrin Van Huff,Sean O'Donnell,Sean O'Donnell
segment,Consumer,Consumer,Corporate,Consumer,Consumer
country,United States,United States,United States,United States,United States
city,Henderson,Henderson,Los Angeles,Fort Lauderdale,Fort Lauderdale


Checking if quanitity is greater than zero for all rows

In [76]:
len(orders[orders['quantity'].astype(int) > 0]) == len(orders)

True

**Profiling findings** (summarize here, and in more detail in your report)

*TODO: write your findings and the design decision each one leads to.*

## 2. Transform: shared cleaning

Clean the data **once**, then build both warehouses from the same clean staging tables.
That way, any difference between the two warehouses comes from the model, not from the cleaning.

Load your result to `staging.orders_clean`, `staging.returns_clean`, and `staging.people_clean` with proper types.

In [77]:
clean = orders.copy()

In [78]:
# TODO: convert types (dates, numbers), trim text, fix the problems you found in profiling.
#the functions below applies the fixes in the previous step
def clean_orders_table(orders:pd.DataFrame)-> pd.DataFrame:
    # Convert date columns to datetime
    orders['order_date'] = pd.to_datetime(orders['order_date'], errors='coerce')
    orders['ship_date'] = pd.to_datetime(orders['ship_date'], errors='coerce')

    # Convert numeric columns to appropriate types
    orders['quantity'] = pd.to_numeric(orders['quantity'], errors='coerce')
    orders['sales'] = pd.to_numeric(orders['sales'], errors='coerce')
    orders['discount'] = pd.to_numeric(orders['discount'], errors='coerce')
    orders['profit'] = pd.to_numeric(orders['profit'], errors='coerce')

    # Trim whitespace from string columns
    str_cols = orders.select_dtypes(include=['object']).columns
    for col in str_cols:
        orders[col] = orders[col].str.strip()

    # Fix postal code issues (ensure 5 digits)
    orders['postal_code'] = orders['postal_code'].astype(str).str.zfill(5)

    # Check quantity, drop rows where quantity is less than or equal to 0
    if len(orders[orders['quantity'].astype(int) > 0]) != len(orders):
        orders.drop(orders[orders['quantity'].astype(int) <= 0].index, inplace=True)

    # restict segment to either consumer, corporate or home office
    valid_segments = ['Consumer', 'Corporate', 'Home Office']
    orders = orders[orders['segment'].isin(valid_segments)]

    # restrict region to either central, east, south or west
    valid_regions = ['Central', 'East', 'South', 'West']
    orders = orders[orders['region'].isin(valid_regions)]

    #restrict ship_mode to either Standard Class, Second Class, First Class or Same Day
    valid_ship_modes = ['Standard Class', 'Second Class', 'First Class', 'Same Day']
    orders = orders[orders['ship_mode'].isin(valid_ship_modes)]

    # Drop rows with missing critical values (e.g., order_id, product_id)
    orders.dropna(subset=['order_id', 'product_id'], inplace=True)

    return orders

def clean_returns_table(returns_df: pd.DataFrame) -> pd.DataFrame:
    valid_returns = ['Yes', 'No']
    returns_df = returns_df[returns_df['returned'].isin(valid_returns)]

    #map return status to boolean
    returns_df['returned'] = returns_df['returned'].map({'Yes': True, 'No': False})
    returns_df['returned'].astype(bool)

    #drop duplicates
    returns_df = returns_df.drop_duplicates()

    return returns_df 

def clean_people_table(people: pd.DataFrame) -> pd.DataFrame:
    #title case for regional_manager
    people['regional_manager'] = people['regional_manager'].str.title()

    #strip leading whitespaces in regional_manager
    people['regional_manager'] = people['regional_manager'].str.strip()

    #drop duplicates 
    people = people.drop_duplicates()

    #ensure region is within [West, East, Central, South]
    valid_regions = ['West', 'East', 'Central', 'South']
    people = people[people['region'].isin(valid_regions)]

    return people 

In [79]:
returns_clean = raw_returns.rename(columns=snake)   # TODO: clean
people_clean  = raw_people.rename(columns=snake)    # TODO: clean

In [80]:
#apply the cleaning step
clean = clean_orders_table(clean)
returns_clean = clean_returns_table(returns_clean)
people = clean_people_table(people_clean)

C:\Users\L\AppData\Local\Temp\ipykernel_18644\979592148.py:15: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  str_cols = orders.select_dtypes(include=['object']).columns


In [81]:
# TODO: add assert statements that stop the pipeline if the data is still invalid
def check_orders_data(clean: pd.DataFrame) -> bool:
    try:
        #row_id uniqueness
        assert clean["row_id"].is_unique 

        #check datatypes
        assert pd.api.types.is_datetime64_any_dtype(clean['order_date']) == True 
        assert pd.api.types.is_datetime64_any_dtype(clean['ship_date']) == True
        assert pd.api.types.is_numeric_dtype(clean['quantity']) == True
        assert pd.api.types.is_numeric_dtype(clean['sales']) == True
        assert pd.api.types.is_numeric_dtype(clean['discount']) == True
        assert pd.api.types.is_numeric_dtype(clean['profit']) == True

        #all postal code entries are 5 digits
        assert len(clean['postal_code'] == 5) == len(clean)

        #quantity must be greater than zero for all rows
        assert len(clean[clean['quantity'].astype(int) > 0]) == len(clean)

        #no missing values 
        assert (clean.isna().sum().sum() == 0) and (clean.isnull().sum().sum() == 0)

        #segment must be either consumer, corporate or home office
        valid_segments = ['Consumer', 'Corporate', 'Home Office']
        assert clean['segment'].isin(valid_segments).all()

        #region must be either central, east, south or west
        valid_regions = ['Central', 'East', 'South', 'West']
        assert clean['region'].isin(valid_regions).all()

        #ship_mode must be either Standard Class, Second Class, First Class or Same Day
        valid_ship_modes = ['Standard Class', 'Second Class', 'First Class', 'Same Day']
        assert clean['ship_mode'].isin(valid_ship_modes).all()

    except AssertionError as e:
        print(e)
        return False
    return True 

def check_returns_data(returns_df: pd.DataFrame) -> bool:
    try:
        assert pd.api.types.is_bool_dtype(returns_df['returned'])
        assert returns_df.duplicated().sum().sum() == 0

    except AssertionError as e:
        print(e)
        return False
    return True

def check_people_data(people:pd.DataFrame) -> bool:
    try:
        assert people.duplicated().sum().sum() == 0
        assert people['region'].isin(['West', 'East', 'Central', 'South']).all()
    except AssertionError as e:
        print(e)
        return False
    return True

In [82]:
print("Orders table check: ", check_orders_data(clean))
print("Returns table check: ", check_returns_data(returns_clean))
print("People table check ", check_people_data(people_clean))

Orders table check:  True
Returns table check:  True
People table check  True


In [83]:
clean.to_csv("clean_orders.csv", index=False)
returns_clean.to_csv("returns_clean.csv", index=False)
people_clean.to_csv("people_clean.csv", index=False)

In [84]:
if check_orders_data(clean) and check_returns_data(returns_clean) and check_people_data(people_clean):
    clean.to_sql("orders_clean", engine, schema="staging", if_exists="replace", index=False,
                dtype={"order_date": sa_types.Date, "ship_date": sa_types.Date, 
                       "quantity": sa_types.SmallInteger, "sales": sa_types.Float, 
                       "discount": sa_types.Float, "profit": sa_types.Float, 
                       "postal_code": sa_types.Integer, "row_id": sa_types.Integer})   # TODO: add the other types
    returns_clean.to_sql("returns_clean", engine, schema="staging", if_exists="replace", index=False)
    people_clean.to_sql("people_clean", engine, schema="staging", if_exists="replace", index=False)

    print(table_counts("staging"))
else:
    print("Data is invalid")

      table_name  row_count
0   orders_clean       9994
1     orders_raw       9994
2   people_clean          4
3     people_raw          4
4  returns_clean        296
5    returns_raw        800


## 3. Inmon architecture: 3NF enterprise warehouse

### 3.1 Physical model (DDL)

Write the `CREATE TABLE` statements for your 3NF model. This DDL implements the physical data model in your report.
Use **at least three PostgreSQL-specific features** and explain each one in the report
(for example identity columns, `CHECK` constraints, `UNIQUE NULLS NOT DISTINCT`, indexes, schemas, comments).

One example table is given so you can see the style. Replace or extend it.

In [85]:
INMON_DDL = r"""
DROP SCHEMA IF EXISTS inmon CASCADE;
CREATE SCHEMA inmon;

CREATE TABLE inmon.segment (
    segment_id   SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    segment_name VARCHAR(20) NOT NULL UNIQUE
);

-- TODO: the rest of your 3NF tables, constraints, and indexes
"""
run_sql(INMON_DDL)

### 3.2 Load the 3NF core

Load parent tables before child tables so that foreign keys resolve.

In [86]:
INMON_LOAD = r"""
INSERT INTO inmon.segment (segment_name)
SELECT DISTINCT segment FROM staging.orders_clean;

-- TODO: load every other table
"""
run_sql(INMON_LOAD)
table_counts("inmon")

,table_name,row_count
0,segment,3


In [87]:
# Reconciliation: prove the warehouse holds exactly what the source holds.
# TODO: change the table and column names to match your model, and add more checks.
checks = {
    # "order lines = source rows": q("SELECT count(*) n FROM inmon.<your_line_table>")["n"][0] == len(clean),
    # "total sales matches": np.isclose(float(q("SELECT sum(sales) s FROM inmon.<your_line_table>")["s"][0]), clean["sales"].sum()),
}
assert all(checks.values()), checks
checks

{}

## 4. Kimball architecture: dimensional model

### 4.1 Declare the model

*TODO: fill in before writing any SQL.*

- **Business process:**
- **Grain (one fact row = ?):**
- **Dimensions:**
- **Facts (measures):**

In [88]:
KIMBALL_DDL = r"""
DROP SCHEMA IF EXISTS kimball CASCADE;
CREATE SCHEMA kimball;

-- TODO: dimension tables, then the fact table, constraints, and indexes
"""
run_sql(KIMBALL_DDL)

### 4.2 Load dimensions, then the fact table

Tip: PostgreSQL's `generate_series()` can build a complete date dimension in a single statement.

In [89]:
KIMBALL_LOAD = r"""
-- TODO: load dimensions first, then the fact table
"""
run_sql(KIMBALL_LOAD)
table_counts("kimball")

ProgrammingError: (psycopg2.ProgrammingError) can't execute an empty query
[SQL: 
-- TODO: load dimensions first, then the fact table
]
(Background on this error at: https://sqlalche.me/e/21/f405)

In [ ]:
# TODO: reconciliation checks for the Kimball warehouse (row count, total sales, total profit)


## 5. Same business questions, both warehouses

Answer each question **twice**: once against the Inmon 3NF warehouse (`inmon` schema) and once against
the Kimball model. Both answers must be identical, and they must match the source data.

1. Total sales and profit by region for each year.
2. Return rate (percentage of order lines that belong to a returned order) and returned sales, by product category.
3. Top 5 customers by sales in 2018, with their segment and number of orders.

In [ ]:
Q1_INMON = """
-- TODO
"""
Q1_KIMBALL = """
-- TODO
"""
q1_i, q1_k = q(Q1_INMON), q(Q1_KIMBALL)
# TODO: assert that q1_i and q1_k give the same numbers, and check one of them against pandas on `clean`
q1_k

In [ ]:
Q2_INMON = """
-- TODO
"""
Q2_KIMBALL = """
-- TODO
"""
q2_i, q2_k = q(Q2_INMON), q(Q2_KIMBALL)
# TODO: assert that q2_i and q2_k give the same numbers, and check one of them against pandas on `clean`
q2_k

In [ ]:
Q3_INMON = """
-- TODO
"""
Q3_KIMBALL = """
-- TODO
"""
q3_i, q3_k = q(Q3_INMON), q(Q3_KIMBALL)
# TODO: assert that q3_i and q3_k give the same numbers, and check one of them against pandas on `clean`
q3_k

In [ ]:
def join_count(sql): return len(re.findall(r"\bJOIN\b", sql, flags=re.I))

comparison = pd.DataFrame({
    "question": ["Q1", "Q2", "Q3"],
    "joins_inmon_3NF": [join_count(s) for s in (Q1_INMON, Q2_INMON, Q3_INMON)],
    "joins_kimball": [join_count(s) for s in (Q1_KIMBALL, Q2_KIMBALL, Q3_KIMBALL)],
})
comparison

## 6. Evidence for the report

Export the tables you will show in your report. Screenshots of query results are also fine.
For the ER diagrams of the *resulting* warehouses, you can generate them from the live database with
pgAdmin (ERD Tool), DBeaver, or DataGrip.

In [ ]:
out = Path("report_outputs"); out.mkdir(exist_ok=True)
table_counts("inmon").to_csv(out / "inmon_row_counts.csv", index=False)
table_counts("kimball").to_csv(out / "kimball_row_counts.csv", index=False)
comparison.to_csv(out / "join_comparison.csv", index=False)
# TODO: export anything else you need (sample rows, query results, profiling table)
sorted(p.name for p in out.iterdir())